title: Adem's Dev Journey
description: Adem's Dev Journey - a developer's journey through the tech world, sharing experiences and insights on software development.
markdown: kramdown

# for atom feed
author:
  name: Adem Kouki
  email: ademkingnew@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# collections_dir: all_collections
# collections:
#   posts:
#     output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
future: true

paginate: 18
paginate_path: /page-:num
