name: Publish Drafts

on:
  schedule:
    - cron: "*/60 * * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test Publish Drafts"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Jekyll Publish Drafts
        uses: soywiz/github-action-jekyll-publish-drafts@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_path: ./
          branch: master
