name: Publish blog drafts

on:
  schedule:
    - cron: "*/60 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Jekyll Publish Drafts
        uses: soywiz/github-action-jekyll-publish-drafts@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_path: ./
          branch: main
